name: Test workflow

on:
  push:
    branches: [ main ]

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzru --delete --delete-excluded --exclude='/.git' --exclude='/.github'
          path: ./
          remote_path: /var/lib/docker-builder/taskie.project
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: copy file via ssh password
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            source: "target/BedWarsLCP-1.0-SNAPSHOT.jar"
            target: "C:\\Users\\orlov\\Documents\\ServerMineTest"
